services:
  nginx:
    image: nginx:stable-bookworm-perl
    restart: always
    ports:
      - 443:443
    networks:
      - koeg-dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - koeg-dev-ssl:/ssl/
networks:
  koeg-dev:
    external: true
volumes:
  koeg-dev-ssl:
    external: true
