services:
  nginx:
    image: nginx:stable-bookworm-perl
    restart: always
    ports:
      - 443:443
      - 3389:3389
      - 25565:25565
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - koeg-dev-ssl:/ssl
    depends_on:
      - wol-script
    network_mode: "host"
  wol-script:
    build: ./wol-script
    restart: always
    ports:
      - 5000:5000
volumes:
  koeg-dev-ssl:
    external: true