events {
}

stream {

    # Forward RDP traffic (port 3389) only if the hostname matches pc.koeg.dev
    server {
        listen 3389;
        proxy_pass 192.168.5.213:3389;
        ssl_preread on;
    }

    # Forward Minecraft traffic (port 25565) to the target server
    server {
        listen 25565;
        proxy_pass 192.168.5.213:25565;
    }
}

http {
    resolver 127.0.0.11;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_certificate /ssl/koeg.dev/certificate.pem;
    ssl_certificate_key /ssl/koeg.dev/private_key.pem;

    server {
        return 403;
    }

    server {
        listen 443 ssl;
        server_name koeg.dev www.koeg.dev;

        location / {
            return 301 https://jam.koeg.dev;
        }
    }

    server {
        listen 443 ssl;
        server_name jam.koeg.dev;

        location / {
            set $backend http://localhost:8080;
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    server {
        listen 443 ssl;
        server_name pc.koeg.dev;

        location / {
            # Forward /start requests to the Flask app running on localhost:5000
            proxy_pass http://localhost:5000/;

            # Optional: Add headers for better proxy handling
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}