events {
}

stream {
    # Forward Minecraft traffic (port 25565) to the target server
    server {
        listen 25565;
        server_name pc.koeg.dev;

        proxy_pass 192.168.5.213:25565;  # Forward to the internal Minecraft server
    }

    # Forward RDP traffic (port 3389) to the target PC (192.168.5.213)
    server {
        listen 3389;
        server_name pc.koeg.dev;

        proxy_pass 192.168.5.213:3389;  # Forward to the RDP server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Forward WOL magic packet (UDP port 9) to the target PC (192.168.5.213)
    server {
        listen 9 udp;  # WOL typically uses UDP port 9
        server_name pc.koeg.dev;

        proxy_pass 192.168.5.213:9;  # Forward WOL packet to internal machine
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

http {
    resolver 127.0.0.11;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_certificate /ssl/koeg.dev/certificate.pem;
    ssl_certificate_key /ssl/koeg.dev/private_key.pem;

    server {
        return 403;
    }

    server {
        listen 443 ssl;
        server_name koeg.dev www.koeg.dev;

        location / {
            return 301 https://jam.koeg.dev;
        }
    }

    server {
        listen 443 ssl;
        server_name jam.koeg.dev;

        location / {
            set $backend http://app:8080;
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
