# Use the official Rust image as the base image
FROM rust:1.85 as builder

# Set the working directory inside the container
WORKDIR /usr/src/wol-script

# Copy the Cargo.toml and Cargo.lock files
COPY Cargo.toml Cargo.lock ./

# Copy the source code
COPY src ./src

# Build the application in release mode
RUN cargo build --release

# Use a minimal base image for the final container
FROM debian:bullseye-slim

# Install necessary dependencies and update glibc
RUN apt-get update && apt-get install -y libssl-dev wget gcc make && \
    wget http://ftp.gnu.org/gnu/libc/glibc-2.34.tar.gz && \
    tar -xvzf glibc-2.34.tar.gz && \
    cd glibc-2.34 && \
    mkdir build && cd build && \
    ../configure --prefix=/usr && \
    make -j$(nproc) && make install && \
    cd / && rm -rf glibc-2.34 glibc-2.34.tar.gz && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /usr/local/bin

# Copy the compiled binary from the builder stage
COPY --from=builder /usr/src/wol-script/target/release/wol-script .

# Expose the port used by the application
EXPOSE 5000

# Set the default command to run the application
CMD ["./wol-script"]